services:
  backend:
    build: .
    container_name: sorteo-back-front
    restart: unless-stopped
    ports:
      - "4000:4000"
    volumes:
      - sorteodb:/app/database
      - sorteouploads:/app/uploads
    environment:
      - NODE_ENV=production
volumes:
  sorteodb:
  sorteouploads:

